# Carga de Datos - Proyecto MLOps

**Objetivo:** Cargar el dataset base y realizar una inspección inicial.

**Dataset:** `Churn_Modelling.csv`

**Flujo:**
1. Importar librerías necesarias
2. Cargar el dataset desde la raíz del proyecto
3. Inspección inicial básica
4. Guardar referencia para el siguiente módulo (EDA)

## 1. Importar Librerías

In [3]:
import pandas as pd
import numpy as np
import os
import sys
from pathlib import Path

# Configurar rutas del proyecto
PROJECT_ROOT = Path(os.getcwd()).parent.parent
DATA_PATH = PROJECT_ROOT / 'data' / 'raw' / 'Churn_Modelling.csv'

print(f"Raíz del proyecto: {PROJECT_ROOT}")
print(f"Ruta del dataset: {DATA_PATH}")
print(f"Archivo existe: {DATA_PATH.exists()}")

Raíz del proyecto: c:\Users\Asus\Desktop\Proyecto
Ruta del dataset: c:\Users\Asus\Desktop\Proyecto\data\raw\Churn_Modelling.csv
Archivo existe: True

## 2. Cargar Dataset

In [4]:
# Cargar el dataset
try:
    df_raw = pd.read_csv(DATA_PATH)
    print("✓ Dataset cargado exitosamente")
    print(f"\nDimensiones: {df_raw.shape[0]} filas x {df_raw.shape[1]} columnas")
except FileNotFoundError:
    print(f"✗ Error: No se encontró el archivo en {DATA_PATH}")
    raise
except Exception as e:
    print(f"✗ Error al cargar el archivo: {str(e)}")
    raise

✓ Dataset cargado exitosamente

Dimensiones: 10000 filas x 14 columnas

## 3. Inspección Inicial

In [5]:
# Vista previa de los primeros registros
print("Primeras 5 filas del dataset:\n")
display(df_raw.head())

Primeras 5 filas del dataset:

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [6]:
# Información general del dataset
print("Información del dataset:\n")
df_raw.info()

Información del dataset:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [7]:
# Nombres de las columnas
print(f"\nColumnas del dataset ({len(df_raw.columns)}):")
for i, col in enumerate(df_raw.columns, 1):
    print(f"{i:2d}. {col}")

Columnas del dataset (14):
 1. RowNumber
 2. CustomerId
 3. Surname
 4. CreditScore
 5. Geography
 6. Gender
 7. Age
 8. Tenure
 9. Balance
10. NumOfProducts
11. HasCrCard
12. IsActiveMember
13. EstimatedSalary
14. Exited

In [8]:
# Estadísticas descriptivas iniciales
print("\nEstadísticas descriptivas (variables numéricas):\n")
display(df_raw.describe())

Estadísticas descriptivas (variables numéricas):

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [9]:
# Verificar valores nulos
print("\nValores nulos por columna:")
null_counts = df_raw.isnull().sum()
null_percentages = (null_counts / len(df_raw)) * 100

null_summary = pd.DataFrame({
    'Nulos': null_counts,
    'Porcentaje': null_percentages
})
display(null_summary[null_summary['Nulos'] > 0])

if null_summary['Nulos'].sum() == 0:
    print("✓ No se detectaron valores nulos explícitos")

Valores nulos por columna:

Empty DataFrame
Columns: [Nulos, Porcentaje]
Index: []

✓ No se detectaron valores nulos explícitos

In [10]:
# Verificar duplicados
duplicates = df_raw.duplicated().sum()
print(f"\nFilas duplicadas: {duplicates}")

if duplicates > 0:
    print(f"Porcentaje de duplicados: {(duplicates / len(df_raw)) * 100:.2f}%")
else:
    print("✓ No se detectaron filas duplicadas")

Filas duplicadas: 0
✓ No se detectaron filas duplicadas

## 4. Resumen de Carga

**Próximos pasos:**
- El dataset `df_raw` está listo para el análisis exploratorio (EDA)
- Continuar con `comprension_eda.ipynb` para análisis detallado

In [11]:
print("="*60)
print("RESUMEN DE CARGA")
print("="*60)
print(f"Dataset: Churn_Modelling.csv")
print(f"Registros: {df_raw.shape[0]:,}")
print(f"Variables: {df_raw.shape[1]}")
print(f"Memoria: {df_raw.memory_usage(deep=True).sum() / 1024**2:.2f} MB")
print(f"\n✓ Carga completada exitosamente")
print("\n→ Continuar con comprension_eda.ipynb")
print("="*60)

============================================================
RESUMEN DE CARGA
============================================================
Dataset: Churn_Modelling.csv
Registros: 10,000
Variables: 14
Memoria: 2.41 MB

✓ Carga completada exitosamente

→ Continuar con comprension_eda.ipynb
============================================================